# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python


name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master  # Change this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: SSH into server and deploy
        uses: ssh username@host
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/debashish/MyDemoFlaskApp/demo-flask-app
            git pull origin master  # Pull the latest changes
            source /home/debashish/MyDemoFlaskApp/demo-flask-app/venv/bin/activate  # Activate virtual environment (if used)
            pip install -r requirements.txt  # Install/update dependencies
            sudo systemctl restart my_app  # Restart the app

